/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CacheCheckResponseDto,
  FontMetaRecord,
  PosterSheetCheckCacheParams,
  PosterSheetRequestDto,
  PosterSheetStatusDto,
  PosterSheetUploadFontBody,
  PreviewRequestDto,
  StartJobResponseDto
} from '../../model';

import { apiFetch } from '../../fetcher';

export type posterSheetStartJobResponse202 = {
  data: StartJobResponseDto
  status: 202
}

export type posterSheetStartJobResponse400 = {
  data: void
  status: 400
}

export type posterSheetStartJobResponse404 = {
  data: void
  status: 404
}

export type posterSheetStartJobResponse422 = {
  data: void
  status: 422
}

export type posterSheetStartJobResponseSuccess = (posterSheetStartJobResponse202) & {
  headers: Headers;
};
export type posterSheetStartJobResponseError = (posterSheetStartJobResponse400 | posterSheetStartJobResponse404 | posterSheetStartJobResponse422) & {
  headers: Headers;
};

export type posterSheetStartJobResponse = (posterSheetStartJobResponseSuccess | posterSheetStartJobResponseError)

export const getPosterSheetStartJobUrl = (id: string,) => {




  return `/JellyfinSuite/PosterSheet/${id}`
}

/**
 * @summary Start Job
 */
export const posterSheetStartJob = async (id: string,
    posterSheetRequestDto: PosterSheetRequestDto, options?: RequestInit): Promise<posterSheetStartJobResponse> => {

  return apiFetch<posterSheetStartJobResponse>(getPosterSheetStartJobUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(posterSheetRequestDto)
  }
);}


export type posterSheetDeleteJobResponse204 = {
  data: void
  status: 204
}

export type posterSheetDeleteJobResponse404 = {
  data: void
  status: 404
}

export type posterSheetDeleteJobResponseSuccess = (posterSheetDeleteJobResponse204) & {
  headers: Headers;
};
export type posterSheetDeleteJobResponseError = (posterSheetDeleteJobResponse404) & {
  headers: Headers;
};

export type posterSheetDeleteJobResponse = (posterSheetDeleteJobResponseSuccess | posterSheetDeleteJobResponseError)

export const getPosterSheetDeleteJobUrl = (id: string,) => {




  return `/JellyfinSuite/PosterSheet/${id}`
}

/**
 * @summary Delete Job
 */
export const posterSheetDeleteJob = async (id: string, options?: RequestInit): Promise<posterSheetDeleteJobResponse> => {

  return apiFetch<posterSheetDeleteJobResponse>(getPosterSheetDeleteJobUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type posterSheetListJobsResponse200 = {
  data: PosterSheetStatusDto[]
  status: 200
}

export type posterSheetListJobsResponseSuccess = (posterSheetListJobsResponse200) & {
  headers: Headers;
};
;

export type posterSheetListJobsResponse = (posterSheetListJobsResponseSuccess)

export const getPosterSheetListJobsUrl = () => {




  return `/JellyfinSuite/PosterSheet/jobs`
}

/**
 * @summary List Jobs
 */
export const posterSheetListJobs = async ( options?: RequestInit): Promise<posterSheetListJobsResponse> => {

  return apiFetch<posterSheetListJobsResponse>(getPosterSheetListJobsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type posterSheetGetStatusResponse200 = {
  data: PosterSheetStatusDto
  status: 200
}

export type posterSheetGetStatusResponse404 = {
  data: void
  status: 404
}

export type posterSheetGetStatusResponseSuccess = (posterSheetGetStatusResponse200) & {
  headers: Headers;
};
export type posterSheetGetStatusResponseError = (posterSheetGetStatusResponse404) & {
  headers: Headers;
};

export type posterSheetGetStatusResponse = (posterSheetGetStatusResponseSuccess | posterSheetGetStatusResponseError)

export const getPosterSheetGetStatusUrl = (jobId: string,) => {




  return `/JellyfinSuite/PosterSheet/${jobId}/status`
}

/**
 * @summary Get Status
 */
export const posterSheetGetStatus = async (jobId: string, options?: RequestInit): Promise<posterSheetGetStatusResponse> => {

  return apiFetch<posterSheetGetStatusResponse>(getPosterSheetGetStatusUrl(jobId),
  {
    ...options,
    method: 'GET'


  }
);}


export type posterSheetGetImageResponse200 = {
  data: Blob
  status: 200
}

export type posterSheetGetImageResponse404 = {
  data: void
  status: 404
}

export type posterSheetGetImageResponse409 = {
  data: void
  status: 409
}

export type posterSheetGetImageResponseSuccess = (posterSheetGetImageResponse200) & {
  headers: Headers;
};
export type posterSheetGetImageResponseError = (posterSheetGetImageResponse404 | posterSheetGetImageResponse409) & {
  headers: Headers;
};

export type posterSheetGetImageResponse = (posterSheetGetImageResponseSuccess | posterSheetGetImageResponseError)

export const getPosterSheetGetImageUrl = (jobId: string,) => {




  return `/JellyfinSuite/PosterSheet/${jobId}/image`
}

/**
 * @summary Get Image
 */
export const posterSheetGetImage = async (jobId: string, options?: RequestInit): Promise<posterSheetGetImageResponse> => {

  return apiFetch<posterSheetGetImageResponse>(getPosterSheetGetImageUrl(jobId),
  {
    ...options,
    method: 'GET'


  }
);}


export type posterSheetStreamStatusResponse200 = {
  data: PosterSheetStatusDto
  status: 200
}

export type posterSheetStreamStatusResponse404 = {
  data: void
  status: 404
}

export type posterSheetStreamStatusResponseSuccess = (posterSheetStreamStatusResponse200) & {
  headers: Headers;
};
export type posterSheetStreamStatusResponseError = (posterSheetStreamStatusResponse404) & {
  headers: Headers;
};

export type posterSheetStreamStatusResponse = (posterSheetStreamStatusResponseSuccess | posterSheetStreamStatusResponseError)

export const getPosterSheetStreamStatusUrl = (jobId: string,) => {




  return `/JellyfinSuite/PosterSheet/${jobId}/stream`
}

/**
 * @summary Stream Status
 */
export const posterSheetStreamStatus = async (jobId: string, options?: RequestInit): Promise<posterSheetStreamStatusResponse> => {

  return apiFetch<posterSheetStreamStatusResponse>(getPosterSheetStreamStatusUrl(jobId),
  {
    ...options,
    method: 'GET'


  }
);}


export type posterSheetPreviewResponse200 = {
  data: Blob
  status: 200
}

export type posterSheetPreviewResponse400 = {
  data: void
  status: 400
}

export type posterSheetPreviewResponse503 = {
  data: void
  status: 503
}

export type posterSheetPreviewResponseSuccess = (posterSheetPreviewResponse200) & {
  headers: Headers;
};
export type posterSheetPreviewResponseError = (posterSheetPreviewResponse400 | posterSheetPreviewResponse503) & {
  headers: Headers;
};

export type posterSheetPreviewResponse = (posterSheetPreviewResponseSuccess | posterSheetPreviewResponseError)

export const getPosterSheetPreviewUrl = () => {




  return `/JellyfinSuite/PosterSheet/preview`
}

/**
 * @summary Preview
 */
export const posterSheetPreview = async (previewRequestDto: PreviewRequestDto, options?: RequestInit): Promise<posterSheetPreviewResponse> => {

  return apiFetch<posterSheetPreviewResponse>(getPosterSheetPreviewUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(previewRequestDto)
  }
);}


export type posterSheetCheckCacheResponse200 = {
  data: CacheCheckResponseDto
  status: 200
}

export type posterSheetCheckCacheResponse204 = {
  data: void
  status: 204
}

export type posterSheetCheckCacheResponseSuccess = (posterSheetCheckCacheResponse200 | posterSheetCheckCacheResponse204) & {
  headers: Headers;
};
;

export type posterSheetCheckCacheResponse = (posterSheetCheckCacheResponseSuccess)

export const getPosterSheetCheckCacheUrl = (itemId: string,
    params?: PosterSheetCheckCacheParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/JellyfinSuite/PosterSheet/cache/${itemId}?${stringifiedParams}` : `/JellyfinSuite/PosterSheet/cache/${itemId}`
}

/**
 * @summary Check Cache
 */
export const posterSheetCheckCache = async (itemId: string,
    params?: PosterSheetCheckCacheParams, options?: RequestInit): Promise<posterSheetCheckCacheResponse> => {

  return apiFetch<posterSheetCheckCacheResponse>(getPosterSheetCheckCacheUrl(itemId,params),
  {
    ...options,
    method: 'GET'


  }
);}


export type posterSheetListFontsResponse200 = {
  data: FontMetaRecord[]
  status: 200
}

export type posterSheetListFontsResponseSuccess = (posterSheetListFontsResponse200) & {
  headers: Headers;
};
;

export type posterSheetListFontsResponse = (posterSheetListFontsResponseSuccess)

export const getPosterSheetListFontsUrl = () => {




  return `/JellyfinSuite/PosterSheet/fonts`
}

/**
 * @summary List Fonts
 */
export const posterSheetListFonts = async ( options?: RequestInit): Promise<posterSheetListFontsResponse> => {

  return apiFetch<posterSheetListFontsResponse>(getPosterSheetListFontsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type posterSheetUploadFontResponse200 = {
  data: FontMetaRecord
  status: 200
}

export type posterSheetUploadFontResponse400 = {
  data: void
  status: 400
}

export type posterSheetUploadFontResponseSuccess = (posterSheetUploadFontResponse200) & {
  headers: Headers;
};
export type posterSheetUploadFontResponseError = (posterSheetUploadFontResponse400) & {
  headers: Headers;
};

export type posterSheetUploadFontResponse = (posterSheetUploadFontResponseSuccess | posterSheetUploadFontResponseError)

export const getPosterSheetUploadFontUrl = () => {




  return `/JellyfinSuite/PosterSheet/fonts`
}

/**
 * @summary Upload Font
 */
export const posterSheetUploadFont = async (posterSheetUploadFontBody: PosterSheetUploadFontBody, options?: RequestInit): Promise<posterSheetUploadFontResponse> => {
    const formData = new FormData();
if(posterSheetUploadFontBody.file !== undefined) {
 formData.append(`file`, posterSheetUploadFontBody.file);
 }

  return apiFetch<posterSheetUploadFontResponse>(getPosterSheetUploadFontUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}


export type posterSheetDeleteFontResponse204 = {
  data: void
  status: 204
}

export type posterSheetDeleteFontResponse400 = {
  data: void
  status: 400
}

export type posterSheetDeleteFontResponse404 = {
  data: void
  status: 404
}

export type posterSheetDeleteFontResponseSuccess = (posterSheetDeleteFontResponse204) & {
  headers: Headers;
};
export type posterSheetDeleteFontResponseError = (posterSheetDeleteFontResponse400 | posterSheetDeleteFontResponse404) & {
  headers: Headers;
};

export type posterSheetDeleteFontResponse = (posterSheetDeleteFontResponseSuccess | posterSheetDeleteFontResponseError)

export const getPosterSheetDeleteFontUrl = (key: string,) => {




  return `/JellyfinSuite/PosterSheet/fonts/${key}`
}

/**
 * @summary Delete Font
 */
export const posterSheetDeleteFont = async (key: string, options?: RequestInit): Promise<posterSheetDeleteFontResponse> => {

  return apiFetch<posterSheetDeleteFontResponse>(getPosterSheetDeleteFontUrl(key),
  {
    ...options,
    method: 'DELETE'


  }
);}


