/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type {
  DeviceListDto,
  ModelDownloadProgressDto,
  ModelDownloadRequestDto,
  ModelListDto,
  OrtActivateRequestDto,
  OrtDownloadProgressDto,
  OrtDownloadRequestDto,
  OrtVersionListDto,
  StitchGetModelDownloadProgressParams,
  StitchGetOrtDownloadProgressParams,
  UpscaleJobDto,
  UpscaleJobLogDto,
  UpscaleStartRequestDto
} from '../../model';

import { apiFetch } from '../../fetcher';

export type stitchGetDevicesResponse200 = {
  data: DeviceListDto
  status: 200
}

export type stitchGetDevicesResponseSuccess = (stitchGetDevicesResponse200) & {
  headers: Headers;
};
;

export type stitchGetDevicesResponse = (stitchGetDevicesResponseSuccess)

export const getStitchGetDevicesUrl = () => {




  return `/JellyfinSuite/Stitch/Devices`
}

/**
 * @summary Get Devices
 */
export const stitchGetDevices = async ( options?: RequestInit): Promise<stitchGetDevicesResponse> => {

  return apiFetch<stitchGetDevicesResponse>(getStitchGetDevicesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type stitchGetModelsResponse200 = {
  data: ModelListDto
  status: 200
}

export type stitchGetModelsResponseSuccess = (stitchGetModelsResponse200) & {
  headers: Headers;
};
;

export type stitchGetModelsResponse = (stitchGetModelsResponseSuccess)

export const getStitchGetModelsUrl = () => {




  return `/JellyfinSuite/Stitch/Models`
}

/**
 * @summary Get Models
 */
export const stitchGetModels = async ( options?: RequestInit): Promise<stitchGetModelsResponse> => {

  return apiFetch<stitchGetModelsResponse>(getStitchGetModelsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type stitchDownloadModelResponse202 = {
  data: void
  status: 202
}

export type stitchDownloadModelResponse404 = {
  data: void
  status: 404
}

export type stitchDownloadModelResponse409 = {
  data: void
  status: 409
}

export type stitchDownloadModelResponseSuccess = (stitchDownloadModelResponse202) & {
  headers: Headers;
};
export type stitchDownloadModelResponseError = (stitchDownloadModelResponse404 | stitchDownloadModelResponse409) & {
  headers: Headers;
};

export type stitchDownloadModelResponse = (stitchDownloadModelResponseSuccess | stitchDownloadModelResponseError)

export const getStitchDownloadModelUrl = () => {




  return `/JellyfinSuite/Stitch/Models/Download`
}

/**
 * @summary Download Model
 */
export const stitchDownloadModel = async (modelDownloadRequestDto: ModelDownloadRequestDto, options?: RequestInit): Promise<stitchDownloadModelResponse> => {

  return apiFetch<stitchDownloadModelResponse>(getStitchDownloadModelUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(modelDownloadRequestDto)
  }
);}


export type stitchGetModelDownloadProgressResponse200 = {
  data: ModelDownloadProgressDto
  status: 200
}

export type stitchGetModelDownloadProgressResponseSuccess = (stitchGetModelDownloadProgressResponse200) & {
  headers: Headers;
};
;

export type stitchGetModelDownloadProgressResponse = (stitchGetModelDownloadProgressResponseSuccess)

export const getStitchGetModelDownloadProgressUrl = (params: StitchGetModelDownloadProgressParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/JellyfinSuite/Stitch/Models/DownloadProgress?${stringifiedParams}` : `/JellyfinSuite/Stitch/Models/DownloadProgress`
}

/**
 * @summary Get Model Download Progress
 */
export const stitchGetModelDownloadProgress = async (params: StitchGetModelDownloadProgressParams, options?: RequestInit): Promise<stitchGetModelDownloadProgressResponse> => {

  return apiFetch<stitchGetModelDownloadProgressResponse>(getStitchGetModelDownloadProgressUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export type stitchDeleteModelResponse200 = {
  data: void
  status: 200
}

export type stitchDeleteModelResponse409 = {
  data: void
  status: 409
}

export type stitchDeleteModelResponseSuccess = (stitchDeleteModelResponse200) & {
  headers: Headers;
};
export type stitchDeleteModelResponseError = (stitchDeleteModelResponse409) & {
  headers: Headers;
};

export type stitchDeleteModelResponse = (stitchDeleteModelResponseSuccess | stitchDeleteModelResponseError)

export const getStitchDeleteModelUrl = (family: string,
    version: string,) => {




  return `/JellyfinSuite/Stitch/Models/${family}/${version}`
}

/**
 * @summary Delete Model
 */
export const stitchDeleteModel = async (family: string,
    version: string, options?: RequestInit): Promise<stitchDeleteModelResponse> => {

  return apiFetch<stitchDeleteModelResponse>(getStitchDeleteModelUrl(family,version),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type stitchGetOrtVersionsResponse200 = {
  data: OrtVersionListDto
  status: 200
}

export type stitchGetOrtVersionsResponseSuccess = (stitchGetOrtVersionsResponse200) & {
  headers: Headers;
};
;

export type stitchGetOrtVersionsResponse = (stitchGetOrtVersionsResponseSuccess)

export const getStitchGetOrtVersionsUrl = () => {




  return `/JellyfinSuite/Stitch/OrtVersions`
}

/**
 * @summary Get Ort Versions
 */
export const stitchGetOrtVersions = async ( options?: RequestInit): Promise<stitchGetOrtVersionsResponse> => {

  return apiFetch<stitchGetOrtVersionsResponse>(getStitchGetOrtVersionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type stitchDownloadOrtVersionResponse202 = {
  data: void
  status: 202
}

export type stitchDownloadOrtVersionResponse404 = {
  data: void
  status: 404
}

export type stitchDownloadOrtVersionResponseSuccess = (stitchDownloadOrtVersionResponse202) & {
  headers: Headers;
};
export type stitchDownloadOrtVersionResponseError = (stitchDownloadOrtVersionResponse404) & {
  headers: Headers;
};

export type stitchDownloadOrtVersionResponse = (stitchDownloadOrtVersionResponseSuccess | stitchDownloadOrtVersionResponseError)

export const getStitchDownloadOrtVersionUrl = () => {




  return `/JellyfinSuite/Stitch/OrtVersions/Download`
}

/**
 * @summary Download Ort Version
 */
export const stitchDownloadOrtVersion = async (ortDownloadRequestDto: OrtDownloadRequestDto, options?: RequestInit): Promise<stitchDownloadOrtVersionResponse> => {

  return apiFetch<stitchDownloadOrtVersionResponse>(getStitchDownloadOrtVersionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(ortDownloadRequestDto)
  }
);}


export type stitchActivateOrtVersionResponse200 = {
  data: void
  status: 200
}

export type stitchActivateOrtVersionResponse404 = {
  data: void
  status: 404
}

export type stitchActivateOrtVersionResponseSuccess = (stitchActivateOrtVersionResponse200) & {
  headers: Headers;
};
export type stitchActivateOrtVersionResponseError = (stitchActivateOrtVersionResponse404) & {
  headers: Headers;
};

export type stitchActivateOrtVersionResponse = (stitchActivateOrtVersionResponseSuccess | stitchActivateOrtVersionResponseError)

export const getStitchActivateOrtVersionUrl = () => {




  return `/JellyfinSuite/Stitch/OrtVersions/Activate`
}

/**
 * @summary Activate Ort Version
 */
export const stitchActivateOrtVersion = async (ortActivateRequestDto: OrtActivateRequestDto, options?: RequestInit): Promise<stitchActivateOrtVersionResponse> => {

  return apiFetch<stitchActivateOrtVersionResponse>(getStitchActivateOrtVersionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(ortActivateRequestDto)
  }
);}


export type stitchGetOrtDownloadProgressResponse200 = {
  data: OrtDownloadProgressDto
  status: 200
}

export type stitchGetOrtDownloadProgressResponseSuccess = (stitchGetOrtDownloadProgressResponse200) & {
  headers: Headers;
};
;

export type stitchGetOrtDownloadProgressResponse = (stitchGetOrtDownloadProgressResponseSuccess)

export const getStitchGetOrtDownloadProgressUrl = (params: StitchGetOrtDownloadProgressParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/JellyfinSuite/Stitch/OrtVersions/DownloadProgress?${stringifiedParams}` : `/JellyfinSuite/Stitch/OrtVersions/DownloadProgress`
}

/**
 * @summary Get Ort Download Progress
 */
export const stitchGetOrtDownloadProgress = async (params: StitchGetOrtDownloadProgressParams, options?: RequestInit): Promise<stitchGetOrtDownloadProgressResponse> => {

  return apiFetch<stitchGetOrtDownloadProgressResponse>(getStitchGetOrtDownloadProgressUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export type stitchStartUpscaleResponse202 = {
  data: UpscaleJobDto
  status: 202
}

export type stitchStartUpscaleResponse404 = {
  data: void
  status: 404
}

export type stitchStartUpscaleResponseSuccess = (stitchStartUpscaleResponse202) & {
  headers: Headers;
};
export type stitchStartUpscaleResponseError = (stitchStartUpscaleResponse404) & {
  headers: Headers;
};

export type stitchStartUpscaleResponse = (stitchStartUpscaleResponseSuccess | stitchStartUpscaleResponseError)

export const getStitchStartUpscaleUrl = () => {




  return `/JellyfinSuite/Stitch/Upscale`
}

/**
 * @summary Start Upscale
 */
export const stitchStartUpscale = async (upscaleStartRequestDto: UpscaleStartRequestDto, options?: RequestInit): Promise<stitchStartUpscaleResponse> => {

  return apiFetch<stitchStartUpscaleResponse>(getStitchStartUpscaleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upscaleStartRequestDto)
  }
);}


export type stitchGetUpscaleStatusResponse200 = {
  data: UpscaleJobDto
  status: 200
}

export type stitchGetUpscaleStatusResponse404 = {
  data: void
  status: 404
}

export type stitchGetUpscaleStatusResponseSuccess = (stitchGetUpscaleStatusResponse200) & {
  headers: Headers;
};
export type stitchGetUpscaleStatusResponseError = (stitchGetUpscaleStatusResponse404) & {
  headers: Headers;
};

export type stitchGetUpscaleStatusResponse = (stitchGetUpscaleStatusResponseSuccess | stitchGetUpscaleStatusResponseError)

export const getStitchGetUpscaleStatusUrl = (jobId: string,) => {




  return `/JellyfinSuite/Stitch/Upscale/${jobId}`
}

/**
 * @summary Get Upscale Status
 */
export const stitchGetUpscaleStatus = async (jobId: string, options?: RequestInit): Promise<stitchGetUpscaleStatusResponse> => {

  return apiFetch<stitchGetUpscaleStatusResponse>(getStitchGetUpscaleStatusUrl(jobId),
  {
    ...options,
    method: 'GET'


  }
);}


export type stitchGetUpscaleResultResponse200 = {
  data: Blob
  status: 200
}

export type stitchGetUpscaleResultResponse404 = {
  data: void
  status: 404
}

export type stitchGetUpscaleResultResponseSuccess = (stitchGetUpscaleResultResponse200) & {
  headers: Headers;
};
export type stitchGetUpscaleResultResponseError = (stitchGetUpscaleResultResponse404) & {
  headers: Headers;
};

export type stitchGetUpscaleResultResponse = (stitchGetUpscaleResultResponseSuccess | stitchGetUpscaleResultResponseError)

export const getStitchGetUpscaleResultUrl = (jobId: string,) => {




  return `/JellyfinSuite/Stitch/Upscale/${jobId}/Result`
}

/**
 * @summary Get Upscale Result
 */
export const stitchGetUpscaleResult = async (jobId: string, options?: RequestInit): Promise<stitchGetUpscaleResultResponse> => {

  return apiFetch<stitchGetUpscaleResultResponse>(getStitchGetUpscaleResultUrl(jobId),
  {
    ...options,
    method: 'GET'


  }
);}


export type stitchGetUpscaleLogResponse200 = {
  data: UpscaleJobLogDto
  status: 200
}

export type stitchGetUpscaleLogResponse404 = {
  data: void
  status: 404
}

export type stitchGetUpscaleLogResponseSuccess = (stitchGetUpscaleLogResponse200) & {
  headers: Headers;
};
export type stitchGetUpscaleLogResponseError = (stitchGetUpscaleLogResponse404) & {
  headers: Headers;
};

export type stitchGetUpscaleLogResponse = (stitchGetUpscaleLogResponseSuccess | stitchGetUpscaleLogResponseError)

export const getStitchGetUpscaleLogUrl = (jobId: string,) => {




  return `/JellyfinSuite/Stitch/Upscale/${jobId}/Log`
}

/**
 * @summary Get Upscale Log
 */
export const stitchGetUpscaleLog = async (jobId: string, options?: RequestInit): Promise<stitchGetUpscaleLogResponse> => {

  return apiFetch<stitchGetUpscaleLogResponse>(getStitchGetUpscaleLogUrl(jobId),
  {
    ...options,
    method: 'GET'


  }
);}


export type stitchCancelUpscaleResponse200 = {
  data: void
  status: 200
}

export type stitchCancelUpscaleResponse404 = {
  data: void
  status: 404
}

export type stitchCancelUpscaleResponseSuccess = (stitchCancelUpscaleResponse200) & {
  headers: Headers;
};
export type stitchCancelUpscaleResponseError = (stitchCancelUpscaleResponse404) & {
  headers: Headers;
};

export type stitchCancelUpscaleResponse = (stitchCancelUpscaleResponseSuccess | stitchCancelUpscaleResponseError)

export const getStitchCancelUpscaleUrl = (jobId: string,) => {




  return `/JellyfinSuite/Stitch/Upscale/${jobId}/Cancel`
}

/**
 * @summary Cancel Upscale
 */
export const stitchCancelUpscale = async (jobId: string, options?: RequestInit): Promise<stitchCancelUpscaleResponse> => {

  return apiFetch<stitchCancelUpscaleResponse>(getStitchCancelUpscaleUrl(jobId),
  {
    ...options,
    method: 'POST'


  }
);}


