/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type {
  FrameIndexDto,
  FrameInfoDto,
  SeekPreviewGetFrameInfoParams,
  SeekPreviewGetFrameParams,
  SeekPreviewReadyStreamParams,
  SeekReadyEvent
} from '../../model';

import { apiFetch } from '../../fetcher';

export type seekPreviewGetFrameResponse200 = {
  data: Blob
  status: 200
}

export type seekPreviewGetFrameResponse404 = {
  data: void
  status: 404
}

export type seekPreviewGetFrameResponse503 = {
  data: void
  status: 503
}

export type seekPreviewGetFrameResponseSuccess = (seekPreviewGetFrameResponse200) & {
  headers: Headers;
};
export type seekPreviewGetFrameResponseError = (seekPreviewGetFrameResponse404 | seekPreviewGetFrameResponse503) & {
  headers: Headers;
};

export type seekPreviewGetFrameResponse = (seekPreviewGetFrameResponseSuccess | seekPreviewGetFrameResponseError)

export const getSeekPreviewGetFrameUrl = (itemId: string,
    params?: SeekPreviewGetFrameParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/JellyfinSuite/SeekPreview/${itemId}?${stringifiedParams}` : `/JellyfinSuite/SeekPreview/${itemId}`
}

/**
 * @summary Get Frame
 */
export const seekPreviewGetFrame = async (itemId: string,
    params?: SeekPreviewGetFrameParams, options?: RequestInit): Promise<seekPreviewGetFrameResponse> => {

  return apiFetch<seekPreviewGetFrameResponse>(getSeekPreviewGetFrameUrl(itemId,params),
  {
    ...options,
    method: 'GET'


  }
);}


export type seekPreviewGetFrameInfoResponse200 = {
  data: FrameInfoDto
  status: 200
}

export type seekPreviewGetFrameInfoResponse404 = {
  data: void
  status: 404
}

export type seekPreviewGetFrameInfoResponse503 = {
  data: void
  status: 503
}

export type seekPreviewGetFrameInfoResponseSuccess = (seekPreviewGetFrameInfoResponse200) & {
  headers: Headers;
};
export type seekPreviewGetFrameInfoResponseError = (seekPreviewGetFrameInfoResponse404 | seekPreviewGetFrameInfoResponse503) & {
  headers: Headers;
};

export type seekPreviewGetFrameInfoResponse = (seekPreviewGetFrameInfoResponseSuccess | seekPreviewGetFrameInfoResponseError)

export const getSeekPreviewGetFrameInfoUrl = (itemId: string,
    params?: SeekPreviewGetFrameInfoParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/JellyfinSuite/SeekPreview/${itemId}/frame-info?${stringifiedParams}` : `/JellyfinSuite/SeekPreview/${itemId}/frame-info`
}

/**
 * @summary Get Frame Info
 */
export const seekPreviewGetFrameInfo = async (itemId: string,
    params?: SeekPreviewGetFrameInfoParams, options?: RequestInit): Promise<seekPreviewGetFrameInfoResponse> => {

  return apiFetch<seekPreviewGetFrameInfoResponse>(getSeekPreviewGetFrameInfoUrl(itemId,params),
  {
    ...options,
    method: 'GET'


  }
);}


export type seekPreviewGetFrameIndexResponse200 = {
  data: FrameIndexDto
  status: 200
}

export type seekPreviewGetFrameIndexResponse404 = {
  data: void
  status: 404
}

export type seekPreviewGetFrameIndexResponse503 = {
  data: void
  status: 503
}

export type seekPreviewGetFrameIndexResponseSuccess = (seekPreviewGetFrameIndexResponse200) & {
  headers: Headers;
};
export type seekPreviewGetFrameIndexResponseError = (seekPreviewGetFrameIndexResponse404 | seekPreviewGetFrameIndexResponse503) & {
  headers: Headers;
};

export type seekPreviewGetFrameIndexResponse = (seekPreviewGetFrameIndexResponseSuccess | seekPreviewGetFrameIndexResponseError)

export const getSeekPreviewGetFrameIndexUrl = (itemId: string,) => {




  return `/JellyfinSuite/SeekPreview/${itemId}/frame-index`
}

/**
 * @summary Get Frame Index
 */
export const seekPreviewGetFrameIndex = async (itemId: string, options?: RequestInit): Promise<seekPreviewGetFrameIndexResponse> => {

  return apiFetch<seekPreviewGetFrameIndexResponse>(getSeekPreviewGetFrameIndexUrl(itemId),
  {
    ...options,
    method: 'GET'


  }
);}


export type seekPreviewReadyStreamResponse200 = {
  data: SeekReadyEvent
  status: 200
}

export type seekPreviewReadyStreamResponse404 = {
  data: void
  status: 404
}

export type seekPreviewReadyStreamResponse503 = {
  data: void
  status: 503
}

export type seekPreviewReadyStreamResponseSuccess = (seekPreviewReadyStreamResponse200) & {
  headers: Headers;
};
export type seekPreviewReadyStreamResponseError = (seekPreviewReadyStreamResponse404 | seekPreviewReadyStreamResponse503) & {
  headers: Headers;
};

export type seekPreviewReadyStreamResponse = (seekPreviewReadyStreamResponseSuccess | seekPreviewReadyStreamResponseError)

export const getSeekPreviewReadyStreamUrl = (itemId: string,
    params?: SeekPreviewReadyStreamParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/JellyfinSuite/SeekPreview/${itemId}/ready-stream?${stringifiedParams}` : `/JellyfinSuite/SeekPreview/${itemId}/ready-stream`
}

/**
 * @summary Ready Stream
 */
export const seekPreviewReadyStream = async (itemId: string,
    params?: SeekPreviewReadyStreamParams, options?: RequestInit): Promise<seekPreviewReadyStreamResponse> => {

  return apiFetch<seekPreviewReadyStreamResponse>(getSeekPreviewReadyStreamUrl(itemId,params),
  {
    ...options,
    method: 'GET'


  }
);}


