/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type {
  PlayHistoryGetParams,
  PlayHistoryResponse
} from '../../model';

import { apiFetch } from '../../fetcher';

export type playHistoryGetResponse200 = {
  data: PlayHistoryResponse
  status: 200
}

export type playHistoryGetResponse401 = {
  data: void
  status: 401
}

export type playHistoryGetResponseSuccess = (playHistoryGetResponse200) & {
  headers: Headers;
};
export type playHistoryGetResponseError = (playHistoryGetResponse401) & {
  headers: Headers;
};

export type playHistoryGetResponse = (playHistoryGetResponseSuccess | playHistoryGetResponseError)

export const getPlayHistoryGetUrl = (params?: PlayHistoryGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/JellyfinSuite/PlayHistory?${stringifiedParams}` : `/JellyfinSuite/PlayHistory`
}

/**
 * @summary Get
 */
export const playHistoryGet = async (params?: PlayHistoryGetParams, options?: RequestInit): Promise<playHistoryGetResponse> => {

  return apiFetch<playHistoryGetResponse>(getPlayHistoryGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


