/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface ComputeDeviceDto {
  id: string;
  displayName: string;
  deviceType: string;
  vendor: string;
  /** @nullable */
  vramMb?: number | null;
  isIntegrated: boolean;
  isDefault: boolean;
  /** @nullable */
  computeCapability?: string | null;
  /** @nullable */
  modelName?: string | null;
  /** @nullable */
  devicePath?: string | null;
}
