/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface ExportParams {
  format: string;
  resizeMode: string;
  /** @nullable */
  customWidth?: number | null;
  /** @nullable */
  customHeight?: number | null;
  resolutionPreset: string;
  speed: number;
  loopCount: number;
  /** @nullable */
  cropX?: number | null;
  /** @nullable */
  cropY?: number | null;
  /** @nullable */
  cropW?: number | null;
  /** @nullable */
  cropH?: number | null;
  quality: number;
}
