/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface FontMetaRecord {
  key: string;
  displayName: string;
  script: string;
  format: string;
  isSerif?: boolean | null;
  isMonospace?: boolean | null;
  isBold?: boolean | null;
  isItalic?: boolean | null;
  hasLigatures?: boolean | null;
}
