/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type { FpsFracDto } from './fpsFracDto';
import type { FrameIndexEntryDto } from './frameIndexEntryDto';

export type FrameIndexStreamEvent = FrameIndexEntryDto[] | {
  fps: FpsFracDto;
};
