/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface FrameExportTaskListItemDto {
  taskId: string;
  itemId: string;
  itemTitle: string;
  type: string;
  status: string;
  /** @nullable */
  resultUrl?: string | null;
  /** @nullable */
  fileSize?: number | null;
  /** @nullable */
  error?: string | null;
  createdAt: number;
  upscaled: boolean;
}
