/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type { ExportParams } from './exportParams';
import type { FrameReference } from './frameReference';

export interface GenerateRequest {
  itemId: string;
  itemTitle: string;
  type: string;
  frames: FrameReference[];
  params: ExportParams;
}
