/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface HwDecodeSettingsDto {
  enabled: boolean;
  deviceStrategy: string;
  supported: boolean;
  /** @nullable */
  unsupportedReason?: string | null;
  multiDeviceAvailable: boolean;
}
