/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export * from './cacheCheckResponseDto';
export * from './computeDeviceDto';
export * from './deviceListDto';
export * from './exportParams';
export * from './fallbackEventDto';
export * from './fontMetaRecord';
export * from './fpsFracDto';
export * from './frameExportGetFrameParams';
export * from './frameExportHealth';
export * from './frameExportTaskListItemDto';
export * from './frameExportTaskProgressParams';
export * from './frameIndexDto';
export * from './frameIndexEntryDto';
export * from './frameIndexStreamEvent';
export * from './frameInfoDto';
export * from './framePairDto';
export * from './frameReference';
export * from './generateRequest';
export * from './generateResponse';
export * from './hwDecodeSettingsDto';
export * from './hwDecodeSettingsUpdateDto';
export * from './jellyfinSuiteFrameInfoStreamParams';
export * from './mediaInfoDto';
export * from './modelDownloadProgressDto';
export * from './modelDownloadRequestDto';
export * from './modelEntryDto';
export * from './modelListDto';
export * from './ortActivateRequestDto';
export * from './ortAssetDto';
export * from './ortDownloadProgressDto';
export * from './ortDownloadRequestDto';
export * from './ortVersionDto';
export * from './ortVersionDtoAssets';
export * from './ortVersionListDto';
export * from './overlaySettings';
export * from './playHistoryEntry';
export * from './playHistoryGetParams';
export * from './playHistoryResponse';
export * from './posterSheetCheckCacheParams';
export * from './posterSheetRequestDto';
export * from './posterSheetStatusDto';
export * from './posterSheetUploadFontBody';
export * from './prefetchRangeEvent';
export * from './prefetchRangeStreamRequest';
export * from './prefetchRequest';
export * from './previewRequestDto';
export * from './qualityThresholds';
export * from './seekPreviewGetFrameInfoParams';
export * from './seekPreviewGetFrameParams';
export * from './seekPreviewReadyStreamParams';
export * from './seekReadyEvent';
export * from './skipSegmentDto';
export * from './startJobResponseDto';
export * from './stitchGetModelDownloadProgressParams';
export * from './stitchGetOrtDownloadProgressParams';
export * from './taskProgressDto';
export * from './upscaleJobDto';
export * from './upscaleJobLogDto';
export * from './upscaleLogDto';
export * from './upscaleStartRequestDto';
