/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface MediaInfoDto {
  filename: string;
  fileSize: string;
  fileSizeBytes: number;
  resolution: string;
  fps: number;
  videoCodec: string;
  /** @nullable */
  bitDepth?: number | null;
  /** @nullable */
  hdrType?: string | null;
  /** @nullable */
  colourSpace?: string | null;
  /** @nullable */
  audioCodec?: string | null;
  /** @nullable */
  audioFormat?: string | null;
  /** @nullable */
  audioBitrate?: string | null;
  /** @nullable */
  audioSampleRate?: number | null;
  audioTracks: number;
  subtitleCount: number;
  duration: string;
}
