/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type { ModelEntryDto } from './modelEntryDto';

export interface ModelListDto {
  models: ModelEntryDto[];
  /** @nullable */
  catalogFetchedAt?: string | null;
  catalogStale: boolean;
}
