/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface ModelEntryDto {
  family: string;
  displayName: string;
  version: string;
  fileName: string;
  /** @nullable */
  fileSizeBytes?: number | null;
  /** @nullable */
  sha256?: string | null;
  /** @nullable */
  downloadUrl?: string | null;
  /** @nullable */
  releaseDate?: string | null;
  status: string;
  /** @nullable */
  localPath?: string | null;
  /** @nullable */
  lastUsedAt?: string | null;
  isLatest: boolean;
}
