/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type { OrtVersionDto } from './ortVersionDto';

export interface OrtVersionListDto {
  /** @nullable */
  activeVersion?: string | null;
  versions: OrtVersionDto[];
  maxRetainedVersions: number;
}
