/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type { OrtVersionDtoAssets } from './ortVersionDtoAssets';

export interface OrtVersionDto {
  version: string;
  /** @nullable */
  releaseDate?: string | null;
  isActive: boolean;
  /** @nullable */
  localDir?: string | null;
  /** @nullable */
  installedAt?: string | null;
  /** @nullable */
  assets?: OrtVersionDtoAssets;
  status: string;
}
