/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface OverlaySettings {
  brandingEnabled: boolean;
  brandingText: string;
  videoInfoEnabled: boolean;
  showFileSize: boolean;
  showResolutionFps: boolean;
  showVideoEncoding: boolean;
  showAudioEncoding: boolean;
  showDuration: boolean;
  showSubtitles: boolean;
  showFrameTimestamp: boolean;
  timestampFont: string;
  timestampBg: boolean;
  timestampShadow: boolean;
  colorTheme: string;
  fontFamily: string;
  brandingLatinFont: string;
  brandingCjkFont: string;
  lang: string;
  timestampPosition: string;
}
