/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export type PlayHistoryGetParams = {
groupBy?: string;
page?: number;
tz?: string;
sortBy?: string;
sortOrder?: string;
mediaType?: string;
showRepeats?: boolean;
groupDedup?: boolean;
pageSize?: number;
};
