/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface PlayHistoryEntry {
  itemId: string;
  playedDate: string;
  /** @nullable */
  title?: string | null;
  mediaType: string;
  /** @nullable */
  favoritedAt?: string | null;
  /** @nullable */
  releaseDate?: string | null;
  /** @nullable */
  addedDate?: string | null;
  /** @nullable */
  seriesName?: string | null;
  /** @nullable */
  seriesId?: string | null;
  /** @nullable */
  seasonNumber?: number | null;
  /** @nullable */
  episodeNumber?: number | null;
  /** @nullable */
  imagePrimaryTag?: string | null;
  hasAncestors: boolean;
  /** @nullable */
  playbackPositionTicks?: number | null;
  /** @nullable */
  videoDuration?: number | null;
}
