/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type { OverlaySettings } from './overlaySettings';
import type { SkipSegmentDto } from './skipSegmentDto';

export interface PosterSheetRequestDto {
  rows: number;
  cols: number;
  mode: string;
  /** @nullable */
  seed?: string | null;
  thumbWidth: number;
  overlay: OverlaySettings;
  /** @nullable */
  skipSegments?: SkipSegmentDto[] | null;
}
