/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export type PosterSheetCheckCacheParams = {
rows?: number;
cols?: number;
thumbWidth?: number;
seed?: string;
overlayHash?: string;
};
