/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type { MediaInfoDto } from './mediaInfoDto';

export interface PosterSheetStatusDto {
  jobId: string;
  itemId: string;
  itemTitle: string;
  status: string;
  progress: number;
  total: number;
  /** @nullable */
  error?: string | null;
  mediaInfo?: MediaInfoDto | null;
  createdAt: number;
}
