/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type { FramePairDto } from './framePairDto';

export interface PrefetchRequest {
  startFrameIdx: number;
  beforeSeconds: number;
  afterSeconds: number;
  includeStart: boolean;
  width: number;
  /** @nullable */
  positions?: number[] | null;
  /** @nullable */
  framePairs?: FramePairDto[] | null;
}
