/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface PrefetchRangeStreamRequest {
  /** @nullable */
  currentTimeMs?: number | null;
  /** @nullable */
  currentFrameIndex?: number | null;
  /** @nullable */
  beforeSeconds?: number | null;
  /** @nullable */
  afterSeconds?: number | null;
  includeCurrentFrame: boolean;
  width: number;
  prefetchSessionId: string;
}
