/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface PrefetchRangeStreamRequest {
  currentTimeMs: number;
  beforeSeconds: number;
  afterSeconds: number;
  includeCurrentFrame: boolean;
  width: number;
}
