/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type { OverlaySettings } from './overlaySettings';

export interface PreviewRequestDto {
  rows: number;
  cols: number;
  thumbWidth: number;
  overlay: OverlaySettings;
}
