/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface TaskProgressDto {
  taskId: string;
  status: string;
  phase: string;
  current: number;
  total: number;
  percent: number;
  /** @nullable */
  resultUrl?: string | null;
  /** @nullable */
  fileSize?: number | null;
  /** @nullable */
  error?: string | null;
}
