/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type { FallbackEventDto } from './fallbackEventDto';

export interface UpscaleLogDto {
  deviceName: string;
  deviceType: string;
  deviceId: string;
  faceRestoreRequested: boolean;
  faceRestoreSkippedNoFace: boolean;
  fallbacks: FallbackEventDto[];
}
