/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type { UpscaleLogDto } from './upscaleLogDto';

export interface UpscaleJobLogDto {
  jobId: string;
  status: string;
  /** @nullable */
  error?: string | null;
  scale: number;
  modelStyle: string;
  faceRestoreRequested: boolean;
  /** @nullable */
  deviceIdRequested?: string | null;
  createdAt: string;
  log?: UpscaleLogDto | null;
}
