/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */

export interface UpscaleJobDto {
  jobId: string;
  status: string;
  percent: number;
  /** @nullable */
  error?: string | null;
  /** @nullable */
  originalUrl?: string | null;
  /** @nullable */
  resultUrl?: string | null;
  /** @nullable */
  originalWidth?: number | null;
  /** @nullable */
  originalHeight?: number | null;
  /** @nullable */
  resultWidth?: number | null;
  /** @nullable */
  resultHeight?: number | null;
  /** @nullable */
  originalSizeBytes?: number | null;
  /** @nullable */
  resultSizeBytes?: number | null;
  faceRestoreSkippedNoFace: boolean;
}
