/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type {
  FrameExportGetFrameParams,
  FrameExportHealth,
  FrameExportTaskListItemDto,
  FrameExportTaskProgressParams,
  GenerateRequest,
  GenerateResponse,
  PrefetchRangeEvent,
  PrefetchRangeStreamRequest,
  PrefetchRequest,
  QualityThresholds,
  TaskProgressDto
} from '../../model';

import { apiFetch } from '../../fetcher';

export type frameExportGetFrameResponse200 = {
  data: Blob
  status: 200
}

export type frameExportGetFrameResponse404 = {
  data: void
  status: 404
}

export type frameExportGetFrameResponse503 = {
  data: void
  status: 503
}

export type frameExportGetFrameResponseSuccess = (frameExportGetFrameResponse200) & {
  headers: Headers;
};
export type frameExportGetFrameResponseError = (frameExportGetFrameResponse404 | frameExportGetFrameResponse503) & {
  headers: Headers;
};

export type frameExportGetFrameResponse = (frameExportGetFrameResponseSuccess | frameExportGetFrameResponseError)

export const getFrameExportGetFrameUrl = (itemId: string,
    params?: FrameExportGetFrameParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/JellyfinSuite/FrameExport/${itemId}?${stringifiedParams}` : `/JellyfinSuite/FrameExport/${itemId}`
}

/**
 * @summary Get Frame
 */
export const frameExportGetFrame = async (itemId: string,
    params?: FrameExportGetFrameParams, options?: RequestInit): Promise<frameExportGetFrameResponse> => {

  return apiFetch<frameExportGetFrameResponse>(getFrameExportGetFrameUrl(itemId,params),
  {
    ...options,
    method: 'GET'


  }
);}


export type frameExportPrefetchResponse202 = {
  data: void
  status: 202
}

export type frameExportPrefetchResponse503 = {
  data: void
  status: 503
}

export type frameExportPrefetchResponseSuccess = (frameExportPrefetchResponse202) & {
  headers: Headers;
};
export type frameExportPrefetchResponseError = (frameExportPrefetchResponse503) & {
  headers: Headers;
};

export type frameExportPrefetchResponse = (frameExportPrefetchResponseSuccess | frameExportPrefetchResponseError)

export const getFrameExportPrefetchUrl = (itemId: string,) => {




  return `/JellyfinSuite/FrameExport/Prefetch/${itemId}`
}

/**
 * @summary Prefetch
 */
export const frameExportPrefetch = async (itemId: string,
    prefetchRequest: PrefetchRequest, options?: RequestInit): Promise<frameExportPrefetchResponse> => {

  return apiFetch<frameExportPrefetchResponse>(getFrameExportPrefetchUrl(itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(prefetchRequest)
  }
);}


export type frameExportPrefetchReadyResponse200 = {
  data: PrefetchRangeEvent
  status: 200
}

export type frameExportPrefetchReadyResponse404 = {
  data: void
  status: 404
}

export type frameExportPrefetchReadyResponse503 = {
  data: void
  status: 503
}

export type frameExportPrefetchReadyResponseSuccess = (frameExportPrefetchReadyResponse200) & {
  headers: Headers;
};
export type frameExportPrefetchReadyResponseError = (frameExportPrefetchReadyResponse404 | frameExportPrefetchReadyResponse503) & {
  headers: Headers;
};

export type frameExportPrefetchReadyResponse = (frameExportPrefetchReadyResponseSuccess | frameExportPrefetchReadyResponseError)

export const getFrameExportPrefetchReadyUrl = (itemId: string,) => {




  return `/JellyfinSuite/FrameExport/PrefetchReady/${itemId}`
}

/**
 * @summary Prefetch Ready
 */
export const frameExportPrefetchReady = async (itemId: string,
    prefetchRangeStreamRequest: PrefetchRangeStreamRequest, options?: RequestInit): Promise<frameExportPrefetchReadyResponse> => {

  return apiFetch<frameExportPrefetchReadyResponse>(getFrameExportPrefetchReadyUrl(itemId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(prefetchRangeStreamRequest)
  }
);}


export type frameExportGenerateResponse202 = {
  data: GenerateResponse
  status: 202
}

export type frameExportGenerateResponse400 = {
  data: void
  status: 400
}

export type frameExportGenerateResponseSuccess = (frameExportGenerateResponse202) & {
  headers: Headers;
};
export type frameExportGenerateResponseError = (frameExportGenerateResponse400) & {
  headers: Headers;
};

export type frameExportGenerateResponse = (frameExportGenerateResponseSuccess | frameExportGenerateResponseError)

export const getFrameExportGenerateUrl = () => {




  return `/JellyfinSuite/FrameExport/Generate`
}

/**
 * @summary Generate
 */
export const frameExportGenerate = async (generateRequest: GenerateRequest, options?: RequestInit): Promise<frameExportGenerateResponse> => {

  return apiFetch<frameExportGenerateResponse>(getFrameExportGenerateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(generateRequest)
  }
);}


export type frameExportTaskProgressResponse200 = {
  data: TaskProgressDto
  status: 200
}

export type frameExportTaskProgressResponse404 = {
  data: void
  status: 404
}

export type frameExportTaskProgressResponseSuccess = (frameExportTaskProgressResponse200) & {
  headers: Headers;
};
export type frameExportTaskProgressResponseError = (frameExportTaskProgressResponse404) & {
  headers: Headers;
};

export type frameExportTaskProgressResponse = (frameExportTaskProgressResponseSuccess | frameExportTaskProgressResponseError)

export const getFrameExportTaskProgressUrl = (params: FrameExportTaskProgressParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/JellyfinSuite/FrameExport/TaskProgress?${stringifiedParams}` : `/JellyfinSuite/FrameExport/TaskProgress`
}

/**
 * @summary Task Progress
 */
export const frameExportTaskProgress = async (params: FrameExportTaskProgressParams, options?: RequestInit): Promise<frameExportTaskProgressResponse> => {

  return apiFetch<frameExportTaskProgressResponse>(getFrameExportTaskProgressUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export type frameExportGetResultResponse200 = {
  data: Blob
  status: 200
}

export type frameExportGetResultResponse404 = {
  data: void
  status: 404
}

export type frameExportGetResultResponse409 = {
  data: void
  status: 409
}

export type frameExportGetResultResponseSuccess = (frameExportGetResultResponse200) & {
  headers: Headers;
};
export type frameExportGetResultResponseError = (frameExportGetResultResponse404 | frameExportGetResultResponse409) & {
  headers: Headers;
};

export type frameExportGetResultResponse = (frameExportGetResultResponseSuccess | frameExportGetResultResponseError)

export const getFrameExportGetResultUrl = (taskId: string,
    filename: string,) => {




  return `/JellyfinSuite/FrameExport/Result/${taskId}/${filename}`
}

/**
 * @summary Get Result
 */
export const frameExportGetResult = async (taskId: string,
    filename: string, options?: RequestInit): Promise<frameExportGetResultResponse> => {

  return apiFetch<frameExportGetResultResponse>(getFrameExportGetResultUrl(taskId,filename),
  {
    ...options,
    method: 'GET'


  }
);}


export type frameExportDeleteResultResponse200 = {
  data: void
  status: 200
}

export type frameExportDeleteResultResponse404 = {
  data: void
  status: 404
}

export type frameExportDeleteResultResponseSuccess = (frameExportDeleteResultResponse200) & {
  headers: Headers;
};
export type frameExportDeleteResultResponseError = (frameExportDeleteResultResponse404) & {
  headers: Headers;
};

export type frameExportDeleteResultResponse = (frameExportDeleteResultResponseSuccess | frameExportDeleteResultResponseError)

export const getFrameExportDeleteResultUrl = (taskId: string,) => {




  return `/JellyfinSuite/FrameExport/Result/${taskId}`
}

/**
 * @summary Delete Result
 */
export const frameExportDeleteResult = async (taskId: string, options?: RequestInit): Promise<frameExportDeleteResultResponse> => {

  return apiFetch<frameExportDeleteResultResponse>(getFrameExportDeleteResultUrl(taskId),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type frameExportCancelResponse200 = {
  data: void
  status: 200
}

export type frameExportCancelResponse404 = {
  data: void
  status: 404
}

export type frameExportCancelResponse409 = {
  data: void
  status: 409
}

export type frameExportCancelResponseSuccess = (frameExportCancelResponse200) & {
  headers: Headers;
};
export type frameExportCancelResponseError = (frameExportCancelResponse404 | frameExportCancelResponse409) & {
  headers: Headers;
};

export type frameExportCancelResponse = (frameExportCancelResponseSuccess | frameExportCancelResponseError)

export const getFrameExportCancelUrl = (taskId: string,) => {




  return `/JellyfinSuite/FrameExport/Cancel/${taskId}`
}

/**
 * @summary Cancel
 */
export const frameExportCancel = async (taskId: string, options?: RequestInit): Promise<frameExportCancelResponse> => {

  return apiFetch<frameExportCancelResponse>(getFrameExportCancelUrl(taskId),
  {
    ...options,
    method: 'POST'


  }
);}


export type frameExportGetTasksResponse200 = {
  data: FrameExportTaskListItemDto[]
  status: 200
}

export type frameExportGetTasksResponseSuccess = (frameExportGetTasksResponse200) & {
  headers: Headers;
};
;

export type frameExportGetTasksResponse = (frameExportGetTasksResponseSuccess)

export const getFrameExportGetTasksUrl = () => {




  return `/JellyfinSuite/FrameExport/Tasks`
}

/**
 * @summary Get Tasks
 */
export const frameExportGetTasks = async ( options?: RequestInit): Promise<frameExportGetTasksResponse> => {

  return apiFetch<frameExportGetTasksResponse>(getFrameExportGetTasksUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type frameExportHealthResponse200 = {
  data: FrameExportHealth
  status: 200
}

export type frameExportHealthResponseSuccess = (frameExportHealthResponse200) & {
  headers: Headers;
};
;

export type frameExportHealthResponse = (frameExportHealthResponseSuccess)

export const getFrameExportHealthUrl = () => {




  return `/JellyfinSuite/FrameExport/Health`
}

/**
 * @summary Health
 */
export const frameExportHealth = async ( options?: RequestInit): Promise<frameExportHealthResponse> => {

  return apiFetch<frameExportHealthResponse>(getFrameExportHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type frameExportDebugResponse200 = {
  data: void
  status: 200
}

export type frameExportDebugResponse503 = {
  data: void
  status: 503
}

export type frameExportDebugResponseSuccess = (frameExportDebugResponse200) & {
  headers: Headers;
};
export type frameExportDebugResponseError = (frameExportDebugResponse503) & {
  headers: Headers;
};

export type frameExportDebugResponse = (frameExportDebugResponseSuccess | frameExportDebugResponseError)

export const getFrameExportDebugUrl = () => {




  return `/JellyfinSuite/FrameExport/Debug`
}

/**
 * @summary Debug
 */
export const frameExportDebug = async ( options?: RequestInit): Promise<frameExportDebugResponse> => {

  return apiFetch<frameExportDebugResponse>(getFrameExportDebugUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type frameExportGetQualityThresholdsResponse200 = {
  data: QualityThresholds
  status: 200
}

export type frameExportGetQualityThresholdsResponseSuccess = (frameExportGetQualityThresholdsResponse200) & {
  headers: Headers;
};
;

export type frameExportGetQualityThresholdsResponse = (frameExportGetQualityThresholdsResponseSuccess)

export const getFrameExportGetQualityThresholdsUrl = () => {




  return `/JellyfinSuite/FrameExport/QualityThresholds`
}

/**
 * @summary Get Quality Thresholds
 */
export const frameExportGetQualityThresholds = async ( options?: RequestInit): Promise<frameExportGetQualityThresholdsResponse> => {

  return apiFetch<frameExportGetQualityThresholdsResponse>(getFrameExportGetQualityThresholdsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type frameExportSetQualityThresholdsResponse200 = {
  data: QualityThresholds
  status: 200
}

export type frameExportSetQualityThresholdsResponseSuccess = (frameExportSetQualityThresholdsResponse200) & {
  headers: Headers;
};
;

export type frameExportSetQualityThresholdsResponse = (frameExportSetQualityThresholdsResponseSuccess)

export const getFrameExportSetQualityThresholdsUrl = () => {




  return `/JellyfinSuite/FrameExport/QualityThresholds`
}

/**
 * @summary Set Quality Thresholds
 */
export const frameExportSetQualityThresholds = async (qualityThresholds: QualityThresholds, options?: RequestInit): Promise<frameExportSetQualityThresholdsResponse> => {

  return apiFetch<frameExportSetQualityThresholdsResponse>(getFrameExportSetQualityThresholdsUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(qualityThresholds)
  }
);}


