/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * JellyfinSuite Plugin API
 * OpenAPI spec version: 1.0.0
 */
import type {
  FrameIndexDto,
  FrameIndexStreamEvent,
  JellyfinSuiteFrameInfoStreamParams
} from '../../model';

import { apiFetch } from '../../fetcher';

export type jellyfinSuiteGetFrameInfoResponse200 = {
  data: FrameIndexDto
  status: 200
}

export type jellyfinSuiteGetFrameInfoResponse404 = {
  data: void
  status: 404
}

export type jellyfinSuiteGetFrameInfoResponse503 = {
  data: void
  status: 503
}

export type jellyfinSuiteGetFrameInfoResponseSuccess = (jellyfinSuiteGetFrameInfoResponse200) & {
  headers: Headers;
};
export type jellyfinSuiteGetFrameInfoResponseError = (jellyfinSuiteGetFrameInfoResponse404 | jellyfinSuiteGetFrameInfoResponse503) & {
  headers: Headers;
};

export type jellyfinSuiteGetFrameInfoResponse = (jellyfinSuiteGetFrameInfoResponseSuccess | jellyfinSuiteGetFrameInfoResponseError)

export const getJellyfinSuiteGetFrameInfoUrl = (itemId: string,) => {




  return `/JellyfinSuite/${itemId}/FrameInfo`
}

/**
 * @summary Get Frame Info
 */
export const jellyfinSuiteGetFrameInfo = async (itemId: string, options?: RequestInit): Promise<jellyfinSuiteGetFrameInfoResponse> => {

  return apiFetch<jellyfinSuiteGetFrameInfoResponse>(getJellyfinSuiteGetFrameInfoUrl(itemId),
  {
    ...options,
    method: 'GET'


  }
);}


export type jellyfinSuiteFrameInfoStreamResponse200 = {
  data: FrameIndexStreamEvent
  status: 200
}

export type jellyfinSuiteFrameInfoStreamResponse404 = {
  data: void
  status: 404
}

export type jellyfinSuiteFrameInfoStreamResponse503 = {
  data: void
  status: 503
}

export type jellyfinSuiteFrameInfoStreamResponseSuccess = (jellyfinSuiteFrameInfoStreamResponse200) & {
  headers: Headers;
};
export type jellyfinSuiteFrameInfoStreamResponseError = (jellyfinSuiteFrameInfoStreamResponse404 | jellyfinSuiteFrameInfoStreamResponse503) & {
  headers: Headers;
};

export type jellyfinSuiteFrameInfoStreamResponse = (jellyfinSuiteFrameInfoStreamResponseSuccess | jellyfinSuiteFrameInfoStreamResponseError)

export const getJellyfinSuiteFrameInfoStreamUrl = (itemId: string,
    params?: JellyfinSuiteFrameInfoStreamParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/JellyfinSuite/${itemId}/FrameInfoStream?${stringifiedParams}` : `/JellyfinSuite/${itemId}/FrameInfoStream`
}

/**
 * @summary Frame Info Stream
 */
export const jellyfinSuiteFrameInfoStream = async (itemId: string,
    params?: JellyfinSuiteFrameInfoStreamParams, options?: RequestInit): Promise<jellyfinSuiteFrameInfoStreamResponse> => {

  return apiFetch<jellyfinSuiteFrameInfoStreamResponse>(getJellyfinSuiteFrameInfoStreamUrl(itemId,params),
  {
    ...options,
    method: 'GET'


  }
);}


